<template>
  <div v-if="!Object.entries(newSecret).length">
    <h2>Hey! What's your secret?</h2>
    <textarea v-model="secret"></textarea>

    <div :class="{'deactived': !secret}">
      <p>Who do you want to send this to?</p>
      <ul class="flex justify-content-center">
        <li v-for="(r, index) in availableRecipients" :key="'recipient-'+ index" :class="{'active': isSelected(r)}">
          <a href="#" @click.prevent="toggle(r)">{{ r }}</a>
        </li>
      </ul>

      <p>How many times do you want this secret to be viewable?</p>
      <input v-model="numberOfShares" type="number" min="3" max="10" />

      <div class="button-wrapper">
        <button @click="store">Share</button>
      </div>
    </div>
  </div>

  <div v-else>
    <h2>Secret saved!</h2>
    <p>Here's the autogenerated link to view your saved secret:</p>
    <a :href="'/#/show/' + newSecret.ID" target="_blank">View</a>
    <a href="#" @click="copyLink">Copy to clipboard</a>
  </div>
</template>

<script>
export default {
  name: 'Home',
  components: { },
  data() {
    return {
      secret: "",
      numberOfShares: 5,
      availableRecipients: ['Nobody'],
      selectedRecipients: ['Nobody'],
      newSecret: {}, // after the secret is saved, this will be populated with the object
      newSecretAddress: "",
    }
  },
  methods: {
    toggle(r) {
      if (r === "Nobody") {
        this.selectedRecipients = ['Nobody'];
        return;
      }

      this.selectedRecipients = this.selectedRecipients.filter((name) => name !== "Nobody");
      this.selectedRecipients.push(r);
    },
    isSelected(r) {
      for (let index = 0; index < this.selectedRecipients.length; index++) {
        if (r === this.selectedRecipients[index]) {
          return true;
        }
      }
      return false;
    },
    store() {
      const postData = new URLSearchParams();
      postData.append("secret", this.secret);
      postData.append("numberOfShares", this.numberOfShares);
      postData.append("shareWith", this.selectedRecipients);

      this.$api.post("/store", postData, {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        }
      }).then((r) => {
        this.newSecret = r.data.secret;
        this.newSecretAddress = r.data.url;
      }).catch(() => {
        // TODO: handle error!
     });
    },
    copyLink() {
      navigator.clipboard.writeText(this.newSecretAddress);
    }
  },
  mounted() {
    this.$api.get("recipients").then((r) => {
      for (let index = 0; index < r.data.length; index++) {
        this.availableRecipients.unshift(r.data[index]);
      }
    })
  }
}
</script>

<style lang="css" scoped>
h2 {
  text-align: left;
  color: white;
}

p {
  color: white;
}

ul {
  margin: 0;
  padding: 0;
  list-style-type: none;
}

button {
  background-color: #6f4bf3;
  color: white;
}

li {
  background-color: #6f4bf3;
  margin: 0 15px;
  display: block;
  border-radius: 3px;
  padding: 5px 15px;
}

li a {
  color: white;
  text-decoration: none;
}

li.active {
  background-color: white;
}

li.active a {
  color: #6f4bf3;
}

.deactived {
  opacity: 0.25;
}
</style>
